#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->make(Kernel::class)->handle(
    $input = new ArgvInput,
    new ConsoleOutput,
);

$app->make(Kernel::class)->terminate($input, $status);

exit($status);
